### ISSUE TITLE
Reduce oauth scopes

### ISSUE THREAD

**Issue by geekgonecrazy** [middlewarehq/unwrapped#139]
## Why do we need this ?

https://github.com/search?q=repo%3Amiddlewarehq%2Funwrapped%20scope&type=code

looks like here is different than in prod where requesting repo read and write

![IMG_9683](https://github.com/middlewarehq/unwrapped/assets/51996/50809b94-cd58-48e3-b6c4-2c48409a8ed4)

## Acceptance Criteria

Shouldn’t request access to write

**Comment by jayantbh** [comment]
Hey @geekgonecrazy!
We heard a lot of this today, and we addressed it! 🎉 
https://unwrapped.dev/ now doesn't **need** you to login to use it.
You still have the option to, but you can generate the cards for anyone to use. 🕺🏽
